import type { CommandFinding, ScanResult } from "./types.js";

export function toJson(result: ScanResult): string {
  return `${JSON.stringify(result, null, 2)}\n`;
}

export function toMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  lines.push("# Command Map", "");
  lines.push(`Generated by cmdmap for \`${result.root}\`.`, "");
  lines.push("## Summary", "");
  lines.push(`- Safe: ${result.summary.safe}`);
  lines.push(`- Caution: ${result.summary.caution}`);
  lines.push(`- Risky: ${result.summary.risky}`, "");
  lines.push("## Recommended verification path", "");
  if (result.recommendedPath.length === 0) lines.push("No safe verification commands found.");
  for (const item of result.recommendedPath) lines.push(`- \`${item.command}\` (${item.kinds.join(", ")})`);
  lines.push("", "## Commands", "");
  lines.push("| Command | Runner | Labels | Safety | Evidence | Notes |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const finding of result.findings) lines.push(row(finding));
  lines.push("");
  return lines.join("\n");
}

function row(finding: CommandFinding): string {
  const cells = [
    codeCell(finding.command),
    tableCell(finding.runner),
    tableCell(finding.kinds.join(", ")),
    tableCell(`${finding.severity} (${finding.confidence})`),
    tableCell(`${finding.evidence.file}:${finding.evidence.line}`),
    tableCell(finding.safetyNotes.join(" ")),
  ];
  return `| ${cells.join(" | ")} |`;
}

function tableCell(value: string): string {
  return value
    .replace(/\\/g, "&#92;")
    .replace(/\|/g, "\\|")
    .replace(/\r\n?|\n/g, "<br>");
}

function codeCell(value: string): string {
  const escaped = tableCell(value);
  const longestRun = Math.max(0, ...Array.from(escaped.matchAll(/`+/g), (match) => match[0].length));
  const delimiter = "`".repeat(longestRun + 1);
  const padding = escaped.startsWith("`") || escaped.endsWith("`") ? " " : "";
  return `${delimiter}${padding}${escaped}${padding}${delimiter}`;
}
