import type { CommandFinding, ScanResult } from "./types.js";

export function toJson(result: ScanResult): string {
  return `${JSON.stringify(result, null, 2)}\n`;
}

export function toMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  lines.push("# Command Map", "");
  lines.push(`Generated by cmdmap for \`${result.root}\`.`, "");
  lines.push("## Summary", "");
  lines.push(`- Safe: ${result.summary.safe}`);
  lines.push(`- Caution: ${result.summary.caution}`);
  lines.push(`- Risky: ${result.summary.risky}`, "");
  lines.push("## Recommended verification path", "");
  if (result.recommendedPath.length === 0) lines.push("No safe verification commands found.");
  for (const item of result.recommendedPath) lines.push(`- \`${item.command}\` (${item.kinds.join(", ")})`);
  lines.push("", "## Commands", "");
  lines.push("| Command | Runner | Labels | Safety | Evidence | Notes |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const finding of result.findings) lines.push(row(finding));
  lines.push("");
  return lines.join("\n");
}

function row(finding: CommandFinding): string {
  const notes = finding.safetyNotes.join(" ").replace(/\|/g, "\\|");
  return `| \`${finding.command}\` | ${finding.runner} | ${finding.kinds.join(", ")} | ${finding.severity} (${finding.confidence}) | ${finding.evidence.file}:${finding.evidence.line} | ${notes} |`;
}
